version: "3.8"
services:
  backend:
    image: "moneebakiani/springboot-react-fullstack:17.9.2021.18.20.29"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev