version: "3.8"
services:
  backend:
    image: "moneebakiani/springboot-react-fullstack:4.9.2021.20.46.33"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev