spring:
  datasource:
    url: 'jdbc:postgresql://aa22v1hon15r07.crjdnejuqwgp.us-east-2.rds.amazonaws.com:5432/student'
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        format_sql: true
server:
  error:
    include-message: always
    include-binding-errors: always